### ISSUE TITLE
Backlight control

### ISSUE THREAD

**Issue by szychor** [travisgoodspeed/md380tools#477]
Is there a way to change that when radio opens squelch  it wont light up LCD ? Its very annoying when im listening it at night  it lights up everytime it  recive call and its too bright .It should light up only when i press keys. Its not very important but if its possible it would be nice to have that option.

**Comment by ispkorte** [comment]
sounds as be a good idea

**Comment by mach327** [comment]
I've added this to the master wish list. 
This can still be discussed here, but closing until there's some work on it. 

I like this idea too, for the same reasons.

**Comment by kd8uxc** [comment]
CROSS POST from: #370 due to the similarity of the request.
Perhaps my request can be combined in the event this request is taken on. My slightly different way about addressing the issue may even satisfy the needs of the OP.

What about a way to turn the light off completely. Then have it only turn on when either the menu button or the back button is pressed. When I am engaged in a QSO or listening I have no need for the light.  As the OP stated it can be very annoying in low light conditions. It's more problematic (even dangerous) in a vehicle at night. I have found myself covering the screen so I don't distract the driver.

**Comment by travisgoodspeed** [comment]
Properly patched by @Wolf-DL4YHF in #651.

**Comment by Wolf-DL4YHF** [comment]
Thanks Travis - I have deleted my temporary branch now.

Am 12.02.2017 um 00:42 schrieb Travis Goodspeed:
