### ISSUE TITLE
MD380G - MD390G - Reported number of DATA Blocks incorrect

### ISSUE THREAD

**Issue by ok2it** [travisgoodspeed/md380tools#769]
Good morning,evening,afternoon gents.

I am not sure this was looked at before here and I am getting more bought by idea that this is bug in original firmware but question is could it be fixed or not?

Behaviour: 
When 380G 390G are configured with GPS position reporting, radio tries to send its location to predefined ID but indicates incorrectly how many DMR UDP blocks it will send.
It says hey RPTR I have 8 blocks - RPTR replys ok send them - TYT send five and session dies because the last 3 will never arrive as they dont exist.

Strange behaviour is HYTERA Repeater - it forwards each block of data regardless of indicated number - so GPS Data goes through.
Also it seems that GPS data are sent through via currently selected channel (TG,ID) as I confirm that TYT390G   to TYT390G GPS position is indicated in DMO and DR mode.

Let me know if I am barking up wrong tree or if I can provide some more data.
73
Jiri OK2IT

**Comment by DL2MF** [comment]
Good morning, yes that issue is a known bug from manufacturer fw. We have not worked on GPS yet, cause as you know all functions are hooked.
It depends on how GPS was configured in your CPS, whether it sends on current channel or uses another one. Works fine when you are on DMO and want to sent your position reports via a repeater.
Might also be worth to have a look to the brandnew stock firmware released 1 or 2 days ago.
