### ISSUE TITLE
Timeslot issue

### ISSUE THREAD

**Issue by KE7EVP** [travisgoodspeed/md380tools#819]
Correction:
When someone comes up on a ts1 talkgroup they come up on all ts1 talkgroups. also
when someone comes up on a ts2 talkgroup they come up on all ts2 talk groups.

**Comment by travisgoodspeed** [comment]
I really don't understand this bug report.  What is going on?

**Comment by danny1990** [comment]
It's nothing to do with timeslots it's just how DMR works.

The only way to do this is to remove all talkgroups from your radio, disable promiscuous mode and change the talkgroup manually each time via the red button menu -> Tk Grp. If in future you want to listen to more than one talkgroup rather than adding the talkgroups back you can enable promiscuous mode from the menu "Utilities -> MD380Tools -> DMR -> Promiscuous".

The only problem is that you will loose the feature of talkgroup names like "World Wide Eng" etc it will just show the talkgroup number instead.
