### ISSUE TITLE
Retevis RT3s - Motorola Basic Privacy compatibility

### ISSUE THREAD

**Issue by 7AAZ** [travisgoodspeed/md380tools#885]
Experimental Firmware

**Comment by travisgoodspeed** [comment]
Insufficient description.  Closing issue.

**Comment by 7AAZ** [comment]
Sorry Travis.....

**Comment by 7AAZ** [comment]
I'm inexperienced here, I needed help on this subject ...

**Comment by travisgoodspeed** [comment]
No worries; this just isn't the proper place.  You should probably write a message to the mailing list, with a complete description of your problem, so that someone can help.

In general, to use Motorola's Basic Privacy, just set the Enhanced Privacy key in your codeplug to the BP key byte, followed by a bunch of zeroes.  The firmware patches in md380tools will then take care of implementing Basic Privacy in Motorola's style with that one byte key.

**Comment by 7AAZ** [comment]
Travis, thank you so much for your support!!! for me it would be easier to explain yourself by email, with your knowledge it could be easy to help me. your email would not be disclosed. If you can please, my email is aax@clix.pt. 73ss !!
