### ISSUE TITLE
Feature Suggestion: Expose more functionality for button assignment (freq up/down, DMR/FM toggle, timeslot toggle)

### ISSUE THREAD

**Issue by blitmap** [travisgoodspeed/md380tools#913]
Hello,

I'm not sure if I am just terrible at reading the manual, but I thought it would be possible to edit/add channels with md380tools (through the '#' key menu).  There is no option to Add Channel or edit the tx/rx frequency of a configured channel.

> I sometimes work in emergency management.  When I'm rolling out to a site I look at RepeaterBook on my iPhone for local repeaters.  I wish it were possible to configure an FM or DMR station on-the-fly without a computer.  In DMR mode I've grown used to toggling Promiscuous mode.  Scan seems to cycle through talkgroups per the selected zone.  I thought this would actually be a frequency scan, heh.

This is a big ask, but I am looking for:
- Exposed functions for button assignment
  - Frequency up/down
  - DMR / FM toggle
  - Timeslot toggle (in DMR mode of course)

- Extend Scanning
  - FM mode - scan by Frequency

- Channels
  - Add Channel through '#' menu
  - Edit existing channels through '#' menu

I am not saying this is a good feature request or I am deserving.  I believe a lot of value would be added because you would not need a computer to configure this.

Am I doing something wrong?  is this already possible?

**Comment by mach327** [comment]
Good ideas! They don't currently exist so you're not missing anything, and I don't think they are trivial with the current state of this project, so it may not happen with the MD-380, but I also want those features.

Unfortunately for the MD-380 in the short term, but fortunately for hams and radio users in the long term, I think most developers have moved on to better things like the [M17 project](https://m17project.org/) and [OpenGD77](https://github.com/rogerclarkmelbourne/OpenGD77).

I'm going to close this since it's not likely to be worked on, but link #370 so we can keep track of the good ideas in that centralized issue.
I think there's a good chance we can get a proper open software or even open hardware handheld in the next decade so we don't have to fight against the manufacturers just to keep our software on the radio, and that's what I'm currently excited for.
