### ISSUE TITLE
Missing D013.034.bin causes failure during `make flash`

### ISSUE THREAD

**Issue by samjbobb** [travisgoodspeed/md380tools#919]
I'm on OS X and have completed the [OS X build environment preparation](https://github.com/travisgoodspeed/md380tools/blob/master/docs/macos.md). 

When I run `make flash`, I get:

```
$ make flash
"/Library/Developer/CommandLineTools/usr/bin/make" -C applet FW=D13_020 all  
echo D13_020 >mark.tmp
"/Library/Developer/CommandLineTools/usr/bin/make" -C lib libstm32f4.a
make[2]: `libstm32f4.a' is up to date.
"/Library/Developer/CommandLineTools/usr/bin/make" -C ../patches/d13.020 patched.img
cd ../../firmware && "/Library/Developer/CommandLineTools/usr/bin/make" unwrapped/D013.020.img
"/Library/Developer/CommandLineTools/usr/bin/make" -f Makefile_orig download
http://w2fbi.com/files/MD380/D013.034.bin => dl/D013.034.bin
make[4]: *** [dl/D013.034.bin] Error 22
make[3]: *** [download] Error 2
make[2]: *** [unwrapped.img] Error 2
make[1]: *** [base.img] Error 2
make: *** [image_D13] Error 2
```

I believe this is because http://w2fbi.com/files/MD380/D013.034.bin, listed in https://github.com/travisgoodspeed/md380tools/blob/master/firmware/firmware_files.txt#L20 has become or is currently unavailable on that server:

```
$ curl -v http://w2fbi.com/files/MD380/D013.034.bin
*   Trying 69.73.181.160...
* TCP_NODELAY set
* Connected to w2fbi.com (69.73.181.160) port 80 (#0)
> GET /files/MD380/D013.034.bin HTTP/1.1
> Host: w2fbi.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Sun, 10 Jan 2021 00:14:37 GMT
< Server: Apache
< Content-Length: 315
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
* Connection #0 to host w2fbi.com left intact
* Closing connection 0
```

Is there another source for that file?

Any other solutions?

Thank you all for your work on this project!

**Comment by tarxvftech** [comment]
Ah, whoops. That's my fault, not sure when that happened but I don't have it on hand anymore either.
I deleted my old github account which removed my access to the repo, and I've been doing stuff with [M17](https://m17project.org/) so I haven't gotten around to asking Travis for access again.

See #795 for original link to D13.034 sources.
And http://tyt888.com/uploadfile/upfiles/20170321134006.zip is the official link, for your convenience.
(Prepare yourself for some pain getting that file, I can't seem to download it because of the super slow transfer and interrupted connections)
